# Generated by Django 4.0.5 on 2022-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0004_rename_user_useractivity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='messages',
            field=models.CharField(max_length=250),
        ),
    ]
