# Generated by Django 4.0.5 on 2022-08-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('op_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.IntegerField(blank=True)),
                ('disease', models.CharField(max_length=100)),
                ('prescription', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_at', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAppointmentForPatientCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement', models.CharField(blank=True, max_length=150)),
                ('prescription', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_at', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dentist_app.patient')),
            ],
        ),
    ]
