"""
Django settings for Dentist project.

Generated by 'django-App_Admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6!*xt=tnbc0o7e3^rh75bvlm%*5lp12kfzl36&a%q1#!@d+l%#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App_Admin',
    'Dentist_app',
    'Patient_app',
    'rest_framework',
    'API_app.apps.API_appConfig',
    'Account.apps.AccountConfig',
    # 'django_db_logger',
    # 'django_apscheduler',
    # 'django_db_log',


]

AUTH_USER_MODEL = 'Account.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# LOGGING = {
# 'version': 1,
# 'disable_existing_loggers': False,
# 'formatters': {
# 'verbose': {
# 'format': '[%(asctime)s] %(levelname)s %(module)s.%(funcName)s %(lineno)d:%(message)s'
# },
# 'simple': {
# 'format': ' %(levelname)s %(message)s',
# },
# },
# 'handlers': {
# 'log_db': {
# 'level': 'ERROR',
# 'class': 'django_db_log.handlers.DBHandler',
# 'model': 'django_db_log.models.ErrorLog',
# 'expiry': 86400,
# 'formatter': 'simple',
# },
# },
# 'loggers': {
# 'django': {
# 'handlers': ['log_db'],
# 'level': 'ERROR',
# 'propagate': False,
# },
# },
# }
#
# INTERVAL_SCHEDULER_JOB_SECONDS = 43200
# GENERAL_LOGS_DELETE_DAYS = 2
# INFO_LOGS_DELETE_DAYS = 2
# DEBUG_LOGS_DELETE_DAYS = 2
# ERROR_LOGS_DELETE_DAYS = 10

#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'main_formatter':{
#             'format': '{asctime} - {levelname} - {module} - {message}',
#             'style': '{',
#         }
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'main_formatter',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': 'info.log',
#             'formatter': 'main_formatter',
#         },
#     },
#     'loggers': {
#         'main': {
#             'handlers': ['file','console'],
#             'propagate': True,
#             'level': 'INFO',
#         },
#     },
#  }


#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
#         },
#         'simple': {
#             'format': '%(levelname)s %(asctime)s %(message)s'
#         },
#     },
#     'handlers': {
#         'db_handler': {
#             'level': 'DEBUG',
#             'class': 'App_Admin.db_log_handler.DatabaseLogHandler',
#             'formatter': 'verbose'
#         }
#     },
#     'loggers': {
#         'db': {
#             'handlers': ['db_handler'],
#             'level': 'DEBUG'
#         }
#     }
# }

# DJANGO_DB_LOGGER_ENABLE_FORMATTER = True
# DJANGO_DB_LOGGER_ADMIN_LIST_PER_PAGE = 30
# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:8081',
# )

ROOT_URLCONF = 'Dentist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dentist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Dentist Application',
        'USER': 'root',
        'PASSWORD': '',
        'OPTIONS': {
                        'sql_mode': 'traditional',
                    }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'anu.thomas@triassicsolutions.com'
# EMAIL_HOST_PASSWORD = 'Ab123456##'
# EMAIL_USE_TLS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'Account.User'