# Generated by Django 4.0.5 on 2022-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0003_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='user',
            new_name='name',
        ),
    ]
